<?php

namespace TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{


    public function showAllCompletedAction(){
        $repo = $this->getDoctrine()->getRepository('TaskBundle:Task');

        $posts = $repo->findAllByCompleted();

        return [
            'posts' => $posts
        ];
    }

}
